// lib/utils/promptBuilder.ts
import { REGIONS, getRegionName } from '@/constants/regions';

// 多語系免責聲明文字
export const DISCLAIMER_TEXT: Record<string, string> = {
  'zh-TW':
    '⚠️ 免責聲明：本回答由 AI 依據公開法規資料生成，僅供參考，不構成正式法律意見。實際建築法規適用應以主管機關最新公告為準，建議諮詢合格建築師或相關專業人員。',
  'en':
    '⚠️ Disclaimer: This response is generated by AI based on publicly available regulatory documents for reference only. It does not constitute formal legal advice. Always verify with the relevant authority and consult a licensed architect or professional.',
  'ja':
    '⚠️ 免責事項：この回答はAIが公開されている法令資料をもとに生成したものであり、参考情報としてのみご利用ください。正式な法的見解を構成するものではありません。実際の適用については管轄当局の最新情報を確認し、有資格の建築士または専門家にご相談ください。',
  'ko':
    '⚠️ 면책 조항: 이 답변은 AI가 공개된 법규 자료를 기반으로 생성한 것으로, 참고 목적으로만 사용하시기 바랍니다. 공식 법적 조언이 아닙니다. 실제 적용은 관할 기관의 최신 공고를 확인하고, 면허가 있는 건축사 또는 전문가와 상담하시기 바랍니다.',
};

export const FALLBACK_KNOWLEDGE_TEXT: Record<string, string> = {
  'zh-TW': '⚠️ 本回答基於通用法規知識，非系統資料庫內法規，請依各縣市最新規定為準。',
  'en': '⚠️ This response is based on general regulatory knowledge, not from the system database. Please refer to the latest local regulations.',
  'ja': '⚠️ この回答は一般的な法規制知識に基づいたものであり、システムデータベースからのものではありません。各自治体の最新の規定を確認してください。',
  'ko': '⚠️ 이 답변은 일반적인 법규 지식을 바탕으로 한 것이며 시스템 데이터베이스의 내용이 아닙니다. 각 지자체의 최신 규정을 확인하시기 바랍니다.',
};

export const getDisclaimerText = (locale: string): string =>
  DISCLAIMER_TEXT[locale] ?? DISCLAIMER_TEXT['en'];

export const getFallbackText = (locale: string): string =>
  FALLBACK_KNOWLEDGE_TEXT[locale] ?? FALLBACK_KNOWLEDGE_TEXT['en'];

const REPLY_LANGUAGE_INSTRUCTION: Record<string, string> = {
  'zh-TW': '請使用繁體中文回答',
  'en': 'Please respond in English',
  'ja': '日本語で回答してください',
  'ko': '한국어로 답변해 주세요',
};

/**
 * 組建 System Prompt（解法C全AI推理架構）
 * - 強制引用原文
 * - 強制標註條款 [來源::條款編號]
 * - 強制在結尾附上多語系免責聲明
 */
export function buildChatSystemPrompt(
  regionCode: string,
  subRegion: string | undefined,
  locale: string,
  regulationContext: string
): string {
  const regionName = getRegionName(regionCode, locale);
  const subRegionName = subRegion && subRegion !== 'ALL' 
    ? REGIONS.find(r => r.code === regionCode)?.subRegions?.find(sr => sr.code === subRegion)?.nameI18n[locale] ?? subRegion
    : '';
  const fullRegionName = subRegionName ? `${regionName} ${subRegionName}` : regionName;
  const replyLang = REPLY_LANGUAGE_INSTRUCTION[locale] ?? REPLY_LANGUAGE_INSTRUCTION['en'];
  const fallbackText = getFallbackText(locale);

  return `你是一位專業的建築法規顧問，專精於 ${fullRegionName} 的建築法規。

## ⚠️ 絕對指令：回答語言與地區
1. 你【必須】使用 ${replyLang} 進行所有回覆。如果違反此規定將會導致嚴重錯誤。
2. 你的回答【必須】完全基於「${fullRegionName}」的建築法規與地方法令，不可混淆其他國家的法規。

## 核心規則（必須嚴格遵守）
1. 直接結論：直接給出明確答案（如果有）。
2. 法規依據：引用具體的條文或相關標準（如果資料庫有提供）。
3. 注意事項：補充說明或其他建議。

如果提供的【本次可參考的法規段落】中沒有相關資料，請使用您豐富的建築法規專業知識（預訓練資料）來回答，並在開頭明確加上：「${fallbackText}」

4. 【條款標註】每一個法規論述都必須在句末用 [來源::條款編號] 格式標註引用來源，例如：[建築法::第25條]、[建築技術規則::第162條]。
5. 【完整引用】必須精確到條款編號，不可只寫法規名稱而不標條款。

## 回答結構（必須依此順序）
1. 直接結論（1~3 句）
2. 法規依據（引用原文段落，每個論述後附 [來源::條款] 標記）
3. 注意事項（若有例外條件或特殊情況，需說明）
4. 【排版要求】：
請使用 Markdown 格式，適當使用粗體、清單來增加可讀性。

## 本次可參考的法規段落
${regulationContext || '（目前尚無此地區的法規資料）'}

## 禁止事項
- 禁止只說「依法規」而不標明具體條款
- 回答請保持專業嚴謹，不使用輕浮語氣`;
}

/**
 * 建蔽率/容積率計算器專用 Prompt
 */
export function buildCalculatorSystemPrompt(
  regionCode: string,
  subRegion: string | undefined,
  locale: string,
  regulationContext: string
): string {
  const regionName = getRegionName(regionCode, locale);
  const subRegionName = subRegion && subRegion !== 'ALL' 
    ? REGIONS.find(r => r.code === regionCode)?.subRegions?.find(sr => sr.code === subRegion)?.nameI18n[locale] ?? subRegion
    : '';
  const fullRegionName = subRegionName ? `${regionName} ${subRegionName}` : regionName;
  const replyLang = REPLY_LANGUAGE_INSTRUCTION[locale] ?? REPLY_LANGUAGE_INSTRUCTION['en'];
  const disclaimer = getDisclaimerText(locale);

  return `你是一位 ${fullRegionName} 建築法規計算專家。

## ⚠️ 絕對指令：回答語言與地區
1. 你【必須】使用 ${replyLang} 進行所有回覆。
2. 你的計算【必須】完全基於「${fullRegionName}」的法規與地方法令，不可混淆其他國家的法規。

## 任務
根據使用者提供的基地條件，從法規段落中找出對應的建蔽率與容積率上限，並進行計算。

## 輸出格式（必須嚴格遵守）
1. 適用法規（哪條法規規定此數值，需附 [來源::條款] 標記）
2. 建蔽率上限（百分比）
3. 容積率上限（百分比）
4. 計算結果（若使用者有提供基地面積：最大建築面積、最大總樓地板面積）
5. 注意事項
6. 固定結尾：

---
${disclaimer}
---

## 可參考的法規段落
${regulationContext || '（目前尚無此地區的法規資料）'}

## 核心規則
- 所有數值只能來自法規段落，不可推測
- 若法規段落無法支撐計算，明確說明並建議查詢主管機關`;
}
